version: '3.8'
services:
  db:
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'splatrank'
    volumes:
      - pgdata13:/var/lib/postgresql/data

volumes:
  pgdata13:
    driver: 'local'
